import Head from 'next/head'
import Image from 'next/image'
import axios from 'axios'
import { useState } from 'react'
import {BsSearch} from 'react-icons/bs'
import Weather from '../components/Weather'

export default function Home() {

  const [city, setCity] = useState('')
  const [weather, setWeather] = useState({})

  const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}&units=metric`

  const fetchWeather = (e) => {
    e.preventDefault()
    axios.get(url).then((response) => {
      setWeather(response.data)
    })
    setCity('')
  }

  return (
    <div>
      <Head>
        <title>Weather Next App</title>
        <meta name='description' content='Generated by create next app'/>
        <link rel='icon' href='/favicon.ico'/>
      </Head>
      
      <div className='absolute top-0 left-0 right-0 bottom-0 bg-black/40 z-[1]'/>

      <Image src='https://images.unsplash.com/photo-1601134467661-3d775b999c8b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1075&q=80'
        fill
        alt='bgImage'
        className='object-cover'
      />

      <div className='relative flex justify-between items-center max-w-[500px] px-2 w-full m-auto pt-20 text-white z-10'>
        <form onSubmit={fetchWeather} className='flex justify-between items-center w-full m-auto p-3 bg-transparent border border-gray-300 text-white rounded-2xl'>
          <div>
            <input onChange={(e) => setCity(e.target.value)} type={'text'} placeholder='Search City' className='bg-transparent border-none text-white focus:outline-none text-2xl'/>
          </div>
          <button><BsSearch size={20}/></button>
        </form>
      </div>

      {weather.main && <Weather data={weather}/>}
      
    </div>
  )
}